### ISSUE TITLE
Error on starting OTP.

### ISSUE THREAD

**Issue by crimsonKss** [toontown-classic/toontown-otp#2]
When i open start_otp.bat file, it gives me this error:
![tt2003otperror](https://user-images.githubusercontent.com/49092373/56464069-dd088980-63b7-11e9-9e3c-8e3ba620d430.png)

**Comment by cmarshall108** [comment]
You have to use a Panda3D build that supports Python2, the OTP implementation currently does not support Python3.

**Comment by crimsonKss** [comment]
i got the Panda3D version with Python2 now, but now it says there's no module named psutils

**Comment by cmarshall108** [comment]
You will need to install the modules it says you are missing via Python's PIP

**Comment by crimsonKss** [comment]
i'm actually trying, i only got to have PIP on python3, python2 doesn't have it by default, and gives me a lot of error when i try to install it with the get-pip.py

**Comment by cmarshall108** [comment]
try running the command `python2_executable -m pip install_command_here`

**Comment by crimsonKss** [comment]
it says no module named pip but i'm still trying

**Comment by crimsonKss** [comment]
fixed it, anyway thank you.

**Comment by xXBentRealityXx** [comment]
Will python 2.7 work with this?

**Comment by cmarshall108** [comment]
@xXBentRealityXx We currently only support Python 2.7 but are planning on moving to Python 3 very soon.

**Comment by xXBentRealityXx** [comment]
@AnythingTechPro Cool man, I'm getting into this after years of World of Warcraft private server development (which is SQL and C++). If you could contact me in discord to help me set up a local network pirates server I'd greatly appreciate it. My Discord tag is Greymane#1398
