### ISSUE TITLE
cant open, help.

### ISSUE THREAD

**Issue by slappygig** [toontown-classic/toontown-otp#4]
When i start the otp batch file, i get this:
https://user-images.githubusercontent.com/96138262/154768070-24245257-901a-4484-b53e-3d7e787e5019.png is link to the screenshot of the error.
I think I installed the pip stuff and why did i get the error?

**Comment by thetestgame** [comment]
It didn't install coloredlogs from pip. Are you sure you installed the requirements.txt file correctly?

**Comment by slappygig** [comment]
i tried to install from the txt but i got
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement coloredlogs (from -r .\requirements.txt (line 1))
Cleaning up...
No distributions at all found for coloredlogs (from -r .\requirements.txt (line 1))
Storing debug log for failure in C:\Users\Olivia\pip\pip.log

**Comment by thetestgame** [comment]
This seems like an issue with your Python/Pip install. coloredlogs is available on pypi https://pypi.org/project/coloredlogs/

**Comment by slappygig** [comment]
Downloading/unpacking coloredlogs
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement coloredlogs
Cleaning up...
No distributions at all found for coloredlogs
Storing debug log for failure in C:\Users\Olivia\pip\pip.log

**Comment by slappygig** [comment]
how do i fix that error no distributions for coloredlogs and where do i start the ai server
